import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Heading from "@/app/components/Heading";
import Nav from "@/app/components/Nav";
import Mascot from "@/app/components/Mascot";
import Gallery from "@/app/components/Gallery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div>
          <Heading />
          <Nav />
          <Gallery />
          <Mascot />
        </div>
      </body>
    </html>
  );
}
